name: e2e tests
on:
  push:
    branches:
      - main
  create: # also run when a new branch is pushed or a tag is created
jobs:
  build:
    name: e2e tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
      - name: Create a release draft for a version tag
        id: create-release-draft
        uses: ./ # because the action is in the same repository we can reference to it by point local directory
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print the URL of the release draft
        # it is implicit assertion because if the output parameter would not be set it would fail
        # NOTE: it looks that it only fails on Windows, on Linux it passes even if the parameter is not returned
        run: echo ${{ steps.create-release-draft.outputs.release-url }} 